# Backbone for the open Phylodiet tree. Ages in Ma, with the source for each node.
STR21 = "Strassert et al. 2021 Nat Commun 12:1879 (MCMCTree AC, Amorphea root, uniform calibrations; mean posterior)"
IRI17 = "Irisarri et al. 2017 Nat Ecol Evol 1:1370 (genome-averaged timetree of jawed vertebrates)"
KIM26 = "Kim et al. 2026 preprint (Ahnfeltia genomes; MCMCtree nuclear BUSCO timetree of red algae, Fig. 2E);"
YANG16 = "Yang et al. 2016 Sci Rep 6:21361 (florideophyte red algae timetree)"
KIM26_SYN = {"Neoporphyra haitanensis": "Pyropia haitanensis", "Aplicata Chile": "Ahnfeltia plicata", "Aborealis Sakhalin": "Ahnfeltia borealis", "Afastigiata Korea": "Ahnfeltia fastigiata"}   # tip labels as in the file (100-Myr units converted to Myr in kim2026_red.nwk)
APPROX = "APPROXIMATE, not yet cited; replace"
MISOF14 = "Misof et al. 2014 Science 346:763 (1KITE insect timetree);"
PETERS17 = "Peters et al. 2017 Curr Biol 27:1013 (Hymenoptera timetree);"
KAWA19 = "Kawahara et al. 2019 PNAS 116:22657 (Lepidoptera timetree);"
WANG16 = "Wang et al. 2016 Sci Rep 6:38939 (insect chronogram evaluated against stem-group fossils);"
WANG16B = "Wang et al. 2016 Cladistics 32:390 (Heteroptera divergences, aquatic lineages);"
WANG17 = "Wang et al. 2019 Cladistics 35:42, online 2017 (Hemiptera-Heteroptera phylogenomics);"
SONG15 = "Song et al. 2015 Cladistics 31:621 (Orthoptera timetree);"
BLAIMER23 = "Blaimer et al. 2023 Nat Commun 14:1212 (Hymenoptera timetree);"
ZHANG18 = "Zhang et al. 2018 Nat Commun 9:205 (Coleoptera timetree);"
WAHL13 = "Wahlberg et al. 2013 PLoS ONE 8:e80875 (Lepidoptera family timetree);"
KAWA23 = " Kawahara et al. 2023 Nat Ecol Evol 7:903 (global butterfly phylogeny);"
TOUSSAINT26 = " Toussaint et al. 2026 Syst Biol, 10.1093/sysbio/syaf029 (skipper butterfly timetree);"
JOHNSON18 = "Johnson et al. 2018 PNAS 115:12775 (hemipteroid phylogenomics, MCMCTree with 23 fossil calibrations);"
WIEG11 = "Wiegmann et al. 2011 PNAS 108:5690 (fly tree of life, penalized-likelihood chronogram, Fig. 3);"
WARE26 = "; J. Ware lab, forthcoming 1KITE Nature ms (pers. comm. 2026-09-27, not yet adopted):"
CHOI24 = "Choi et al. 2024 Curr Biol 34:740 (plastome brown algal timetree, uncorrelated clock, 8 fossil calibrations; Table 3);"
SHEN20 = "Shen et al. 2020 Sci Adv 6:eabd0079 (1,107-genome Ascomycota timetree, RelTime, six calibrations);"
TT5 = "TimeTree 5 (Kumar et al. 2022 Mol Biol Evol 39:msac174), median of published estimates; used by permission of the TimeTree team, 2026-09-21;"
TANNER17 = "Tanner et al. 2017 Proc R Soc B 284:20162818 (180-gene cephalopod timetree, CIR clock, 12 calibrations; Suppl. Table 2 and Fig. S4);"
ZHANG22 = "Frontiers Ecol Evol 2022, 10.3389/fevo.2022.973485 (mitogenomic gastropod timetree, ML dating);"
LI25 = "Li et al. 2025 Syst Biol 74:16 (UCE bivalve timetree, MCMCTree, 18 calibrations from Crouch et al. 2021);"
WOLFE19 = "Wolfe et al. 2019 Proc R Soc B 286:20190079, PhyloBayes UGAM chronogram;"
# Subtrees (S) keep their own internal ages and hang from the enclosing node at their crown age.
# Rule: a source's crown wins over a backbone node for the same split; backbone ages apply only above it.
# Nodes with no source or species under them persist as placeholders so curation.PLACEMENTS_OPEN can anchor families to them.
import os as _os
OPEN = _os.environ.get("PHYLODIET_SOURCES", _os.environ.get("PHYLOPLATE_SOURCES", "sources/"))   # folder holding the downloaded source chronograms (not in the repo)
import csv as _csv

SB18_SYN = {"Achnatherum hymenoides": "Eriocoma hymenoides", "Amomum tsao-ko": "Lanxangia tsaoko",
            "Chaenomeles sinensis": "Pseudocydonia sinensis", "Erythranthe guttata": "Mimulus guttatus",
            "Cheilocostus speciosus": "Hellenia speciosa"}
RAB18_SYN = {"Liza haematocheila": "Planiliza haematocheila", "Chelon haematocheilus": "Planiliza haematocheila",
             "Sciaena gilberti": "Cilus gilberti", "Channa obscura": "Parachanna obscura"}
UPH19_SYN = {"Bubalus arnee": "Bubalus bubalis", "Tragelaphus oryx": "Taurotragus oryx", "Equus africanus": "Equus asinus",
             "Macropus rufus": "Osphranter rufus", "Macropus rufogriseus": "Notamacropus rufogriseus"}
VAR19_SYN = {"Polyporus squamosus": "Cerioporus squamosus"}
for _r in _csv.DictReader(open(OPEN + "Species_name_match.csv", encoding="utf-8"), delimiter="\t"):
    _a, _f = _r["Alignment_names"].replace("_", " "), _r["Species_names_final"].replace("_", " ")
    if _a != _f: VAR19_SYN.setdefault(_a, _f)
JETZ12_SYN = {"Puffinus griseus": "Ardenna grisea", "Puffinus tenuirostris": "Ardenna tenuirostris",
              "Larus ridibundus": "Chroicocephalus ridibundus", "Anas penelope": "Mareca penelope",
              "Anas strepera": "Mareca strepera", "Anas clypeata": "Spatula clypeata", "Tetrao tetrix": "Lyrurus tetrix",
              "Bonasa bonasia": "Tetrastes bonasia", "Francolinus capensis": "Pternistis capensis",
              "Collocalia fuciphaga": "Aerodramus fuciphagus"}

TREE = N("Eukaryotes", 2132, STR21,
  N("Amorphea", 1938, STR21,
    N("Opisthokonta", 1359, STR21,
      N("Fungi", 806, STR21,
        N("Mucoromycota + Dikarya", 700, "T. James (U Michigan), pers. comm. 2026-09-22: ~700 from the literature; Szantho et al. 2025 Nat Ecol Evol give 701-1114 for the LCA",
          N("Dikarya", 646, STR21,
            S(OPEN + "shen2020_asco.nwk", "Shen et al. 2020 Sci Adv 6:eabd0079, 1,107-genome Ascomycota timetree (RelTime, 815 genes; exact times)", {"Galactomyces candidus": "Geotrichum candidum"}, groups=["Fungi"]),
            N("Basidiomycota", 452, STR21,
              S(OPEN + "varga2019.tree", "Varga et al. 2019 Nat Ecol Evol 3:668, FastDate chronogram 216 (5,284 Agaricomycotina)", VAR19_SYN),
            ),
          ),
        ),
      ),
      N("Animals", 688, STR21,
        N("Cnidaria + Bilateria", 651, STR21,
          N("Cnidaria", 620, APPROX + " (Anthozoa vs Medusozoa; Park et al. 2012 give 741, above the STR21 stem)"),
          N("Bilateria", 616, STR21,
            N("Protostomes", 592, STR21,
              N("Ecdysozoa", 585, APPROX,
                N("Arthropoda", 555, APPROX + " (cf. Lozano-Fernandez et al. 2016)",
                  N("Chelicerata", 480, APPROX,
                    N("Arachnida", 450, APPROX),
                  ),
                  N("Mandibulata", 545, APPROX,
                    N("Pancrustacea", 520, APPROX + " (cf. Misof et al. 2014)",
                      N("Multicrustacea", 510, APPROX,
                        N("Cirripedia", 193, TT5 + " barnacle crown 193; my prior guess 300"),
                        N("Malacostraca", 490, APPROX + " (Wolfe et al. 2019 stomatopod/decapod split 466-480)",
                          N("Eumalacostraca", 480, APPROX,
                           N("Eucarida", 470, APPROX,
                            N("Decapoda", 465, WOLFE19 + " 465 (CIR 455)",
                              N("Dendrobranchiata", 349, WOLFE19 + " 349 (CIR 361)"),
                              N("Pleocyemata", 461, WOLFE19 + " 461 (CIR 454)",
                                N("Caridea", 415, WOLFE19 + " 415 (CIR 432)"),
                                N("Reptantia", 402, WOLFE19 + " 402 (CIR 393)",
                                  N("Achelata", 250, WOLFE19 + " 250 (CIR 254)",
                                    N("Palinuridae", 110, WOLFE19 + " Panulirus vs Palinurus 110 (CIR 167)"),
                                  ),
                                  N("Astacidea", 223, WOLFE19 + " 223 (CIR 322; models disagree)",
                                    N("Crayfish (Astacoidea + Parastacoidea)", 149, WOLFE19 + " Procambarus vs Cherax 149 (CIR 241)"),
                                  ),
                                  N("Meiura", 322, WOLFE19 + " 322 (CIR 329)",
                                    N("Anomura", 197, WOLFE19 + " 197 (CIR 206)"),
                                    N("Brachyura", 183, WOLFE19 + " 183 (CIR 162)",
                                      N("Eubrachyura", 102, WOLFE19 + " 102 (CIR 118)"),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      ),
                      N("Hexapoda", 479, MISOF14 + " origin of insects ~479 (Early Ordovician)" + WARE26 + " ~523",
                        N("Insecta", 441, MISOF14 + " Archaeognatha split ~441" + WARE26 + " ~523",
                         N("Pterygota", 406, MISOF14 + " insect flight ~406 (Early Devonian); Thomas et al. 2013 Syst Biol 62:285 give 385" + WARE26 + " ~470s",
                          N("Neoptera", 383, WANG16 + " Neoptera ~383" + WARE26 + " ~475",
                            N("Polyneoptera", 350, APPROX + " (Termitidae joins here; Bourguignon et al. 2015 MBE 32:406 date Termitidae vs Coptotermitinae+Heterotermitinae ~67, crown Termitidae ~54)" + WARE26 + " 425+",
                              N("Orthoptera", 300, APPROX + " (cf. Song et al. 2015)",
                                N("Ensifera", 268, SONG15 + " Gryllidae vs Tettigoniidae ~268"),
                                N("Acrididae + Pyrgomorphidae", 140, SONG15 + " ~140"),
                              ),
                            ),
                            N("Eumetabola", 373, WANG16 + " Eumetabola ~373",
                              N("Hemiptera", 362, JOHNSON18 + " Heteroptera vs Auchenorrhyncha+Coleorrhyncha ~362, read from Fig. 1 (the cicadas join here; crown Hemiptera incl. Sternorrhyncha 386, 95% CI 354-427; Johnson's interior ages run older than Misof et al. 2014)",
                                N("Cicadidae", 199, WANG17 + " crown Cicadidae ~199; " + JOHNSON18 + " crown Auchenorrhyncha ~309, Cicadomorpha ~247, Cercopoidea vs Cicadoidea ~216 (Fig. 1)"),
                                N("Heteroptera", 293, JOHNSON18 + " Nepomorpha vs Leptopodomorpha+Cimicomorpha+Pentatomomorpha ~293, read from Fig. 1 (crown Heteroptera incl. Gerromorpha and Dipsocoromorpha ~309; Cimicomorpha vs Pentatomomorpha ~250; crown Pentatomomorpha ~200)",
                                  N("Nepomorpha", 243, WANG17 + " Belostomatidae vs Corixidae ~243; " + JOHNSON18 + " Corixoidea vs Nepoidea+Ochteroidea ~212, crown Nepomorpha ~192 (Fig. 1)"),
                                  N("Pentatomoidea", 100.5, WANG16B + " Pentatomidae vs Tessaratomidae ~100.5; " + JOHNSON18 + " crown Pentatomoidea ~93 (Fig. 1)"),
                                ),
                              ),
                              N("Holometabola", 345, MISOF14 + " major extant lineages ~345 (Mississippian)",
                                N("Hymenoptera", 281, PETERS17 + " crown Hymenoptera ~281" + WARE26 + " ~298; " + BLAIMER23 + " 280.0 (267.1-287.9); Apocrita 226.6",
                                  N("Aculeata", 142.3, BLAIMER23 + " crown Aculeata 142.3 (129.1-157.6), Table 1 node 26 (Chrysidoidea, not in the food tree, is the first branch)",
                                    N("Vespoidea + Apoidea + Formicoidea", 123, BLAIMER23 + " Vespoidea vs the remaining non-chrysidoid aculeates ~123, Fig. 2 node 28 read against the time axis",
                                      N("Vespoidea", 108.6, BLAIMER23 + " crown Vespoidea 108.6 (92.7-123.9), Table 1 node 53 (Vespidae vs Rhopalosomatidae; the v0.17 sheet carried this as crown Vespidae)",
                                        N("Vespidae", 80, BLAIMER23 + " Fig. 2 collapses the 7 sampled Vespidae to a triangle whose apex reads ~80; the subfamilies sampled are not listed in the main text, so this stands in for the Polistinae vs Vespinae split until a Vespidae timetree is in hand"),
                                      ),
                                      N("Apoidea + Formicoidea", 108, BLAIMER23 + " Apoidea vs Formicidae ~108, Fig. 2 node 31 read against the time axis (crown Apoidea 102.1 (98.5-120.9), Table 1 node 32; the ants join here as a polytomy, which puts their crown at 108 against 103-124 in Borowiec et al. 2019 Mol Phylogenet Evol 134:111)",
                                        N("Apidae", 87, "Cardinal & Danforth 2011 Proc R Soc B 278:1717: crown corbiculate bees 87 (78-95), the common ancestor in which eusociality arose; Apini vs Meliponini sits at or just below it (Blaimer et al. 2023 Fig. 2 reads the crown of all bees at ~70 and of its 12 Apidae at ~55, younger than most bee studies)"),
                                      ),
                                    ),
                                  ),
                                ),
                                N("Aparaglossata", 338, APPROX + " (must sit below Holometabola 345)",
                                  N("Coleoptera", 300, ZHANG18 + " crown Coleoptera ~300 (Dytiscidae joins here; its crown ~170)",
                                    N("Polyphaga", 260, APPROX + " (cf. Zhang et al. 2018)",
                                      N("Cucujiformia", 200, ZHANG18 + " Tenebrionidae vs Curculionidae ~200 (Curculionidae crown ~120, one genus listed)",
                                        N("Tenebrionidae", 122, ZHANG18 + " crown Tenebrionidae ~122"),
                                      ),
                                      N("Scarabaeidae", 120, ZHANG18 + " crown Scarabaeidae ~120"),
                                    ),
                                  ),
                                  N("Panorpida", 320, APPROX + " (Diptera vs Lepidoptera; must sit above Lepidoptera crown 300)",
                                    N("Diptera", 238, WIEG11 + " Culicomorpha+Psychodomorpha+Ptychopteridae vs Perissommatidae+Bibionomorpha+Brachycera ~238, read from Fig. 3 (Chaoboridae vs Stratiomyidae; crown Diptera ~247, Deuterophlebiidae first; the lower-Diptera radiation spans ~245-227, called 220 in the abstract; crown Brachycera ~204, Stratiomyomorpha leaves the other lower Brachycera ~196; family crowns ~129 Brammer & von Dohlen 2007 MPE 43:660 and ~118 Bertone et al. 2008 Syst Entomol 33:668, one species each)"),
                                    N("Lepidoptera", 300, KAWA19 + " crown Lepidoptera 299.5 (312.4-276.4), Late Carboniferous; crown Ditrysia 154.7 (172.1-137.5) and Apoditrysia 118.5 (132.1-105.6) carry no food tips of their own",
                                      N("Cossoidea + Obtectomera", 111, KAWA19 + " Sesioidea+Zygaenoidea+Cossoidea vs Obtectomera ~111, read from Fig. 1 (two nodes inside the Apoditrysia crown of 118.5; the SZC crown reads ~106)",
                                        N("Cossidae", 95, KAWA19 + " Fig. 1: the Hypoptinae lineage (Givira; our Comadia) and the Australian cossids (Culama, Archaeoses; our Endoxyla) separate at ~92-95, with Castniidae and Megalopygidae nested among them; Wahlberg et al. 2013 gave ~120, which cannot sit under the 111 split above"),
                                        N("Obtectomera", 108, KAWA19 + " Papilionoidea vs the remaining Obtectomera ~108, read from Fig. 1 (Hesperiidae joins here; crown Papilionoidea 98.3 (110.3-86.9), Hesperiidae+Hedylidae 84.4;" + KAWA23 + " crown Papilionoidea 101.4 (102.5-100.0);" + TOUSSAINT26 + " Hesperiidae vs Hedylidae 83 (87-79), crown Hesperiidae 65 (69-62), for when a second skipper is listed)",
                                          N("Bombycoidea", 88, WAHL13 + " Bombycidae vs Saturniidae ~88 (Kawahara et al. 2019 Fig. 1 reads ~71)",
                                            N("Saturniidae", 70, WAHL13 + " Saturniidae ~70"),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                         ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              N("Lophotrochozoa", 564, STR21,
                N("Annelida", 520, APPROX + " (TimeTree 5 gives 631, older than STR21 Lophotrochozoa 564; left as is)"),
                N("Mollusca", 545, APPROX + " (Polyplacophora split; must sit above Conchifera)",
                  N("Conchifera", 534, STR21 + " (Lottia vs Octopus = conchiferan crown)",
                    N("Bivalvia", 485, LI25 + " crown Bivalvia ~485",
                      N("Pteriomorphia", 446, LI25 + " Pectinida vs other pteriomorphians 446 (410-474)",
                        N("Ostreida + Arcida + Mytilida", 421, LI25 + " Ostreida vs Mytilida 421 (384-458)"),
                      ),
                      N("Heterodonta", 470, LI25 + " deep heterodont nodes 467-525",
                        N("Imparidentia", 400, APPROX + " (between Euheterodonta 467 and the 362 node)",
                          N("Core Imparidentia", 362, LI25 + " (Myida+Venerida) vs (Galeommatida+Adapedonta+Cardiida) 362 (310-414)",
                            N("Myida + Venerida", 301, LI25 + " 301 (249-358)"),
                            N("Adapedonta + Cardiida", 300, LI25 + " ~300 (250-348)"),
                          ),
                        ),
                      ),
                    ),
                    N("Gastropoda", 532, ZHANG22 + " Patellogastropoda split 532 (505-548); topology after Uribe et al. 2022 Syst Biol, Cunha & Giribet 2019 differ at the root",
                      N("Orthogastropoda", 493, ZHANG22 + " Vetigastropoda vs Caenogastropoda+relatives 493 (460-521)",
                        N("Vetigastropoda", 370, TANNER17 + " Fig. S4 95% CI 311-432, midpoint"),
                        N("Apogastropoda", 394, TANNER17 + " Fig. S4 95% CI 351-437, midpoint (Caenogastropoda vs Heterobranchia)",
                          N("Caenogastropoda", 260, TANNER17 + " Fig. S4 95% CI 140-310; set at 260 to sit above the TimeTree Neogastropoda crown of 239",
                            N("Neogastropoda", 239, TT5 + " 239; my prior guess 150"),
                          ),
                          N("Heterobranchia", 300, APPROX,
                            N("Stylommatophora", 150, APPROX),
                          ),
                        ),
                      ),
                    ),
                    N("Coleoidea", 289, TANNER17 + " crown Coleoidea 289",
                      N("Octobrachia", 239, TANNER17 + " crown Octobrachia 239 (vampire squid vs octopods)",
                        N("Incirrata", 98, TANNER17 + " crown Incirrata 98"),
                      ),
                      N("Decabrachia", 173, TANNER17 + " crown Decabrachia 173",
                        N("Myopsida", 100, TANNER17 + " Myopsida 100"),
                        N("Oegopsida", 104, TANNER17 + " Oegopsida 104"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            N("Deuterostomes", 599, STR21,
              N("Echinodermata", 500, APPROX,
                N("Echinozoa", 450, APPROX,
                  N("Echinoidea", 113, TT5 + " 113; my prior guess 250"),
                  N("Holothuroidea", 250, APPROX),
                ),
              ),
              N("Chordates", 560, STR21,
                N("Olfactores", 545, APPROX,
                  N("Tunicata", 300, APPROX),
                  N("Vertebrates", 535, APPROX + " (cyclostome/gnathostome split)",
                    N("Cyclostomata", 480, APPROX),
                    N("Jawed vertebrates", 458, IRI17,
                      S(OPEN + "sharks_vertlife.nwk", "Stein et al. 2018 Nat Ecol Evol 2:288, VertLife shark tree subset (Chond_10Cal), tree 1 of 100", {"Raja binoculata": "Beringraja binoculata", "Himantura gerrardi": "Maculabatis gerrardi"}),
                      N("Bony vertebrates", 449, IRI17,
                        S(OPEN + "actinopt_12k_treePL_tre", "Rabosky et al. 2018 Nature 559:392, Fish Tree of Life actinopt_12k_treePL", RAB18_SYN),
                        N("Lobe-finned fishes + tetrapods", 412, IRI17,
                          T("Protopterus annectens"),
                          N("Tetrapods", 350, IRI17 + " (early Carboniferous; mean approx.)",
                            S(OPEN + "amphibians_vertlife.nwk", "Jetz & Pyron 2018 Nat Ecol Evol 2:850, VertLife amphibian tree subset, tree 1 of 100", {}),
                            N("Amniotes", 325, STR21,
                              S(OPEN + "mamphy_mcc.nwk", "Upham et al. 2019 PLoS Biol 17:e3000494, MamPhy completed 5,911sp NDexp MCC", UPH19_SYN),   # github.com/n8upham/MamPhy_v1/_DATA/MamPhy_fullPosterior_BDvr_Completed_5911sp_topoCons_NDexp_MCC_v2_target.tre (NEXUS; first tree as Newick)
                              N("Sauropsids", 280, APPROX + " (lepidosaur/archosaur split)",
                                S(OPEN + "squamates_vertlife.nwk", "Tonini et al. 2016 Biol Conserv 204:23, VertLife squamate tree subset, tree 1 of 100", {}),
                                N("Archosaurs + turtles", 260, APPROX,
                                  N("Testudines", 200, APPROX),
                                  N("Archosaurs", 250, APPROX + " (crocodilians vs birds)",
                                    N("Crocodylia", 90, APPROX),
                                    S(OPEN + "birds_jetz_tree1.nwk", "Jetz et al. 2012 Nature 491:444, birdtree.org Ericson Stage 2 subset, tree 1 of 100", JETZ12_SYN),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
  N("Diaphoretickes + Discoba", 2114, STR21,
    N("Discoba", 1674, STR21, T("Euglena gracilis")),
    N("Diaphoretickes", 2028, STR21,
      N("SAR", 1741, STR21,
        N("Stramenopiles", 1044, STR21,
          N("Phaeophyceae", 371, CHOI24 + " crown Phaeophyceae 371 (275-474); origin vs Schizocladia 449",
            N("Ishigeales + SSD + BACR", 308, CHOI24 + " 308",
              N("SSD + BACR", 224, CHOI24 + " 224 (177-275)",
                N("BACR", 167, CHOI24 + " brown algal crown radiation 167 (130-206)",
                  N("BACR II-V", 142, CHOI24 + " 142",
                    N("Fucales", 66, CHOI24 + " crown Fucales 66"),
                    N("BACR III-V", 132, CHOI24 + " 132",
                      N("Ectocarpales + Laminariales", 103, CHOI24 + " 103",
                        N("Ectocarpales", 54, CHOI24 + " crown Ectocarpales 54"),
                        N("Laminariales", 83, CHOI24 + " crown Laminariales 83"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      N("Archaeplastida", 1925, STR21,
        N("Rhodophyta", 1614, STR21,
          N("Bangiophyceae + Florideophyceae", 1415, STR21 + " (the Kim et al. 2026 source below puts the Bangiales-Florideophyceae split at ~996; its crown hangs here)",
            S(OPEN + "kim2026_red.nwk", "Kim et al. 2026 preprint, posterior-mean tree of the correlated-clock MCMCtree analysis (nuclear BUSCOs, 70 red algae, Fig. 2E); tree file provided by Hocheol Kim, 2026-09-28", KIM26_SYN, groups=["Red algae"]),
          ),
        ),
        N("Viridiplantae", 1112, STR21,
          N("Chlorophyta", 972, STR21,
            N("Core Chlorophyta (UTC)", 850, APPROX + " REVIEW (raised to 850 to sit above TimeTree Trebouxiophyceae 827): Strassert node 206 (Coccomyxa vs Volvox) gives 583, but Del Cortona et al. 2020 PNAS and Hou et al. 2022 Nat Commun place the origin of green seaweeds in the Tonian-Cryogenian (>720); topology follows them (Bryopsidales sister to Chlorophyceae, Ulvophyceae s.s. separate)",
              N("Ulvophyceae s.s.", 700, APPROX + " (Tonian-Cryogenian origin per Del Cortona 2020 / Hou 2022)",
                N("Ulvales", 609, TT5 + " Ulva vs Monostroma 609; consistent with Del Cortona 2020 / Hou 2022"),
              ),
              N("Bryopsidales + Chlorophyceae", 750, APPROX + " (topology per Del Cortona 2020)",
                N("Bryopsidales", 400, APPROX),
                N("Chlorophyceae", 400, APPROX),
              ),
              N("Trebouxiophyceae", 827, TT5 + " Chlorella vs Prasiola 827"),
            ),
          ),
          N("Streptophyta", 790, STR21,
            N("Land plants", 534, STR21,
              N("Euphyllophytes", 480, STR21 + " (474; raised to 480 to sit above FTOL's fern crown of 475)",
                S(OPEN + "ftol_dated.nwk", "Nitta et al. 2022 Front Plant Sci, FTOL ML dated tree (ftolr)", {}, groups=["Ferns"]),   # github.com/fernphy/ftol_data ftol_sanger_ml_dated.tre
                S(OPEN + "v0.1/ALLMB.tre", "Smith & Brown 2018 Am J Bot 105:302, ALLMB (seed plants, Magallon backbone)", SB18_SYN),   # github.com/FePhyFoFum/big_seed_plant_trees release v0.1.zip
              ),
            ),
          ),
        ),
      ),
    ),
  ),
)
